name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    ignore_paths:
      - README.md
      - Makefile
      - .gitignore
      - .python-version
      - .vscode/**
      - site/**
      - .pytest_cache/**
      - .mypy_cache/**
      - .coverage
      - .coverage.*
      - .coverage.*.*
      - .coverage.*.*.*

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: github-pages
      url: https://mauricioromagnollo.github.io/developer-hero

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build
# ==========
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Cleanup
        run: rm -rf ./site  # Optional: Clean up the generated site

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: ./site
      #     cname: mauricioromagnollo.github.io
